# ArgoCD Application for E-commerce Stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspnet-ecommerce
  namespace: argocd
spec:
  project: default
  # Source configuration
  source:
    repoURL: https://gitlab.com/BunlongCHEA/Ecommerce-DotNet.git
    targetRevision: HEAD
    path: Deploy/k8s/app
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true