# Production Let's Encrypt ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/instance: aspnet-ecommerce
  annotations:
    # Skip ArgoCD validation for cert-manager resources
    argocd.argoproj.io/sync-options: Validate=false,Replace=true
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications
    email: chea.bunlong.cloud1@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx  # Uses nginx-ingress for HTTP-01 challenge